USE table_home_work;
SELECT * FROM PRODUCTS;

SELECT PRODUCTNAME, MANUFACTURER, PRICE
FROM PRODUCTS
WHERE PRODUCTCOUNT > 2;

SELECT * FROM PRODUCTS
WHERE MANUFACTURER = "SAMSUNG"; 

SELECT * FROM PRODUCTS
WHERE PRODUCTNAME LIKE "%Iphone%";

SELECT * FROM PRODUCTS
WHERE MANUFACTURER LIKE '%SAMSUNG%';

SELECT * FROM PRODUCTS
WHERE PRODUCTNAME RLIKE '[:DIGIT:]';

SELECT * FROM PRODUCTS
WHERE PRODUCTNAME RLIKE '8';